# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonts',
            new_name='Font',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='font',
            old_name='nome',
            new_name='name',
        ),
    ]
