# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonte', '0002_auto_20171128_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='font',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
