# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonte', '0005_auto_20171128_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
